apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
  namespace: dev
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:postgres@postgres.dev.svc.cluster.local:5432/app
  JWT_SECRET: local-dev-secret
